[mypy]
python_version = 3.11
pretty = True
show_error_codes = True
ignore_missing_imports = True
warn_unused_ignores = True
warn_redundant_casts = True
no_implicit_optional = True

# + Ajouts
disallow_untyped_defs = True          # exige des annotations partout (entrée + sortie)
disallow_incomplete_defs = True       # interdit les annotations “partielles”
warn_return_any = True                # crie si le type de retour devient Any
# … options du palier 1 …
disallow_untyped_calls = True         # empêcher d’appeler avec des args non typés
disallow_any_generics = True          # List/Dict nues interdites (exige List[int], Dict[str, …])
warn_unused_configs = True